# Generated by Django 4.1.5 on 2023-02-13 01:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_remove_variant_precio_compra_and_more'),
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carrito',
        ),
    ]
