# Generated by Django 4.1.5 on 2023-02-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
