# Generated by Django 4.1.5 on 2023-03-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_delete_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ganancia',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentaje de ganancia'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
