# Generated by Django 4.1.5 on 2023-03-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cliente_telefono_alter_cliente_first_name_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, default='Consumidor final', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cliente'),
        ),
    ]
