# Generated by Django 4.1.5 on 2023-03-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')], default='EFECTIVO', max_length=8),
        ),
    ]
