# Generated by Django 4.1.5 on 2023-03-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_medio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO')], default='EFECTIVO', max_length=9),
        ),
    ]
