# Generated by Django 4.1.5 on 2023-03-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='estado',
            field=models.CharField(default='CREADO', max_length=10),
        ),
    ]
