# Generated by Django 4.1.5 on 2023-03-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'CREADO'), ('PAGADO', 'PAGADO'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')], default='CREADO', max_length=10),
        ),
    ]
