# Generated by Django 4.1.5 on 2023-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_detalleventa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='estado',
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'CREADO'), ('PAGADO', 'PAGADO'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')], default='CREADO', max_length=10),
        ),
    ]
