# Generated by Django 4.1.5 on 2023-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='genero',
        ),
        migrations.AddField(
            model_name='product',
            name='genero',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=6),
        ),
    ]
