# Generated by Django 4.1.5 on 2023-02-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_variant_genero_product_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='product',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
