# Generated by Django 4.1.5 on 2023-02-10 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='catalogos/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('talle', models.CharField(max_length=50)),
                ('precio_menor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_mayor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant_minima', models.PositiveIntegerField(default=1)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('recibido', models.BooleanField(default=False)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('factura', models.FileField(blank=True, upload_to='facturas')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto')),
            ],
        ),
    ]
